<?php

namespace BienesBundle\Repository;

/**
 * JurisdiccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JurisdiccionRepository extends \Doctrine\ORM\EntityRepository
{
}
