<?php

namespace BienesBundle\Repository;

/**
 * RamaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RamaRepository extends \Doctrine\ORM\EntityRepository
{
}
