<?php

namespace BienesBundle\Repository;

/**
 * ResponsableAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponsableAreaRepository extends \Doctrine\ORM\EntityRepository
{
}
