bienes:
    resource: "@BienesBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

logout:
    path: /logout

login_check:
  path: /check

login:
    path:     /login
    defaults: { _controller: BienesBundle:Login:login }


