# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        BienesBundle\Entity\User:
            algorithm: bcrypt


    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
            our_db_provider:
                entity:
                    class: BienesBundle:User

    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: /logout
                target: /
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false


            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
