# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        BienesBundle\Entity\User:
            algorithm: bcrypt

        BienesBundle\Security\User:
            algorithm: bcrypt

        Symfony\Component\Security\Core\User\User: plaintext

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        users:
            chain:
                providers: [users_in_memory , proveedor_usuario ]
        proveedor_usuario: 
            id: BienesBundle\Security\UserProvider
        users_in_memory:
            memory:
                users:
                    admin:
                        password: 'admin'
                        roles: 'ROLE_ADMIN'
                    admin2:
                        password: 'admin2'
                        roles: 'ROLE_ADMIN'
        
    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /check
                post_only: true
                
                failure_path: null
                failure_forward: false
                always_use_default_target_path: true
                default_target_path: /
            logout:
                path: /logout
                #target: /login
                target: /
            remember_me:
                secret: '%secret%'
                lifetime: 604800 # 1 week in seconds
                path: /
                # por defecto, esta funcionalidad está disponible en una
                # checkbox en el formulario de login, descomenta la
                # siguiente línea para activarlo siempre.
                #always_remember_me: true
            access_denied_url: /denegado
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false


            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    role_hierarchy:
    #    ROLE_SUPERADMIN: ROLE_ADMIN
        ROLE_ADMIN: ROLE_USUARIO

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/denegado, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/factura, roles: ROLE_ADMIN }
        #- { path: ^/bien, roles: ROLE_SUPERADMIN }
        - { path: ^/user, roles: ROLE_ADMIN }
        - { path: ^/responsable, roles: ROLE_ADMIN }
        - { path: ^/responsableArea, roles: ROLE_ADMIN }
        - { path: ^/tipo, roles: ROLE_ADMIN }
        - { path: ^/rama, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USUARIO }