doctrine:
    dbal:
        default_connection: ruinstituciones
        connections:
            default:
                # configure these for your database server
                url: '%env(resolve:DATABASE_URL)%'
                mapping_types:
                        enum: string
                        set: string
                        varbinary: string
                        tinyblob: text
                        
            ruinstituciones:
                # configure these for your database server
                url: '%env(resolve:DATABASE_URL_INSTITUCIONES)%'
                mapping_types:
                        enum: string
                        set: string
                        varbinary: string
                        tinyblob: text           

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    
    orm:
         
        default_entity_manager: default
        entity_managers:
            ruinstituciones:
                connection: ruinstituciones
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/ruinstituciones'
                        prefix: 'App\Entity\ruinstituciones'
                        alias: App
                        
            tablas_comunes:
                connection: default
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/tablascomunes'
                        prefix: 'App\Entity\tablascomunes'
                        alias: App            
            
            default:
                connection: default
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                        
            
