factura_index:
    path:     /
    defaults: { _controller: "BienesBundle:Factura:index" }
    methods:  GET

factura_show:
    path:     /{id}/show
    defaults: { _controller: "BienesBundle:Factura:show" }
    methods:  GET

factura_new:
    path:     /new
    defaults: { _controller: "BienesBundle:Factura:new" }
    methods:  [GET, POST]

factura_edit:
    path:     /{id}/edit
    defaults: { _controller: "BienesBundle:Factura:edit" }
    methods:  [GET, POST]

factura_delete:
    path:     /{id}/delete
    defaults: { _controller: "BienesBundle:Factura:delete" }
    methods:  DELETE

factura_imprimir:
    path:     /{id}/imprimir
    defaults: { _controller: "BienesBundle:Factura:imprimir" }
    methods:  [GET, POST]