responsablearea_index:
    path:     /
    defaults: { _controller: "BienesBundle:ResponsableArea:index" }
    methods:  GET

responsablearea_show:
    path:     /{id}/show
    defaults: { _controller: "BienesBundle:ResponsableArea:show" }
    methods:  GET

responsablearea_new:
    path:     /new
    defaults: { _controller: "BienesBundle:ResponsableArea:new" }
    methods:  [GET, POST]

responsablearea_edit:
    path:     /{id}/edit
    defaults: { _controller: "BienesBundle:ResponsableArea:edit" }
    methods:  [GET, POST]

responsablearea_delete:
    path:     /{id}/delete
    defaults: { _controller: "BienesBundle:ResponsableArea:delete" }
    methods:  DELETE
