responsable_index:
    path:     /
    defaults: { _controller: "BienesBundle:Responsable:index" }
    methods:  GET

responsable_show:
    path:     /{id}/show
    defaults: { _controller: "BienesBundle:Responsable:show" }
    methods:  GET

responsable_new:
    path:     /new
    defaults: { _controller: "BienesBundle:Responsable:new" }
    methods:  [GET, POST]

responsable_edit:
    path:     /{id}/edit
    defaults: { _controller: "BienesBundle:Responsable:edit" }
    methods:  [GET, POST]

responsable_delete:
    path:     /{id}/delete
    defaults: { _controller: "BienesBundle:Responsable:delete" }
    methods:  DELETE
