ubicacion_index:
    path:     /
    defaults: { _controller: "BienesBundle:Ubicacion:index" }
    methods:  GET

ubicacion_show:
    path:     /{id}/show
    defaults: { _controller: "BienesBundle:Ubicacion:show" }
    methods:  GET

ubicacion_new:
    path:     /new
    defaults: { _controller: "BienesBundle:Ubicacion:new" }
    methods:  [GET, POST]

ubicacion_edit:
    path:     /{id}/edit
    defaults: { _controller: "BienesBundle:Ubicacion:edit" }
    methods:  [GET, POST]

ubicacion_delete:
    path:     /{id}/delete
    defaults: { _controller: "BienesBundle:Ubicacion:delete" }
    methods:  DELETE
