bienes_bien:
    resource: "@BienesBundle/Resources/config/routing/bien.yml"
    prefix:   /bien

bienes_factura:
    resource: "@BienesBundle/Resources/config/routing/factura.yml"
    prefix:   /factura


bienes_proveedor:
    resource: "@BienesBundle/Resources/config/routing/proveedor.yml"
    prefix:   /proveedor

bienes_tipo:
    resource: "@BienesBundle/Resources/config/routing/tipo.yml"
    prefix:   /tipo

bienes_tipoRama:
    resource: "@BienesBundle/Resources/config/routing/rama.yml"
    prefix:   /rama

bienes_responsable:
    resource: "@BienesBundle/Resources/config/routing/responsable.yml"
    prefix:   /responsable

bienes_responsableA:
    resource: "@BienesBundle/Resources/config/routing/responsableArea.yml"
    prefix:   /responsableA

bienes_ubicacion:
    resource: "@BienesBundle/Resources/config/routing/ubicacion.yml"
    prefix:   /ubicacion

bienes_homepage:
    path:     /
    defaults: { _controller: BienesBundle:Default:index }



user_registration:
    path:     /register
    defaults: { _controller: BienesBundle:Registro:register }

