bienes_factura:
    resource: "@BienesBundle/Resources/config/routing/factura.yml"
    prefix:   /factura


bienes_proveedor:
    resource: "@BienesBundle/Resources/config/routing/proveedor.yml"
    prefix:   /proveedor

bienes_homepage:
    path:     /
    defaults: { _controller: BienesBundle:Default:index }
