-- MySQL Script generated by MySQL Workbench
-- jue 01 jul 2021 11:56:53 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema desoc_buenaspracticas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema desoc_buenaspracticas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `desoc_buenaspracticas` DEFAULT CHARACTER SET latin1 COLLATE latin1_spanish_ci ;
-- -----------------------------------------------------
-- Schema mds_ruinstituciones
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mds_ruinstituciones
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mds_ruinstituciones` DEFAULT CHARACTER SET latin1 ;
-- -----------------------------------------------------
-- Schema mds_tablas_comunes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mds_tablas_comunes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mds_tablas_comunes` DEFAULT CHARACTER SET latin1 ;
USE `desoc_buenaspracticas` ;

-- -----------------------------------------------------
-- Table `desoc_buenaspracticas`.`estadoActoAdministrativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desoc_buenaspracticas`.`estadoActoAdministrativo` (
  `idestado` INT NOT NULL AUTO_INCREMENT,
  `estadoDescripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idestado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `desoc_buenaspracticas`.`tipoSolicitante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desoc_buenaspracticas`.`tipoSolicitante` (
  `idtipoSolicitante` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipoSolicitante`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `desoc_buenaspracticas`.`Institucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desoc_buenaspracticas`.`Institucion` (
  `inst_id` INT(11) NOT NULL AUTO_INCREMENT,
  `doctrine_version` INT(11) NOT NULL DEFAULT '1',
  `id_institucion` INT(11) NULL DEFAULT NULL,
  `inst_nom` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `inst_nom_abr` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `inst_pag_web` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `inst_mail` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `inst_telefono` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `inst_celular` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `inst_fec_fun` DATE NULL DEFAULT NULL,
  `inst_cuit_cdi` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `inst_sit_iva` ENUM('No posee', 'Resp. Inscripto', 'Exento', 'Otros') CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `inst_nro_sipaf` INT(11) NULL DEFAULT NULL,
  `inst_estatuto` TINYINT(1) NULL DEFAULT NULL,
  `inst_nro_rong` INT(11) NULL DEFAULT NULL,
  `inst_nro_rong_fec` DATE NULL DEFAULT NULL,
  `inst_sede_fisica` ENUM('Central', 'Filial') CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `inst_sede_fisica_nro` INT(11) NULL DEFAULT NULL,
  `inst_ocu_sede` ENUM('Propia', 'Cedida', 'Alquilada - Uso exclusiva', 'Alquilada - Uso compartido') CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `inst_alcance_act` ENUM('Nacional', 'Regional', 'Local') CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `inst_amb_trab` ENUM('Urbano', 'Suburbano', 'Rural') CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `inst_beneficiarios_act` ENUM('Toda la comunidad', 'Integrantes de la institucion', 'Otras instituciones', 'Sin beneficiarios directos') CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `inst_pob_otros` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `inst_tip_act_otros` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `inst_origen_datos` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `inst_rec_mat_otros` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `inst_area_tem_otros` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `inst_dir_calle` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `inst_dir_nro` INT(11) NULL DEFAULT NULL,
  `inst_dir_piso` INT(11) NULL DEFAULT NULL,
  `inst_zon_trab` ENUM('Localidad Origen', 'Varias Localidades', 'Toda la Provincia') CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `inst_tema_otros` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `inst_dir_dpto_ofi_casa` ENUM('Dpto', 'Oficina', 'Casa') CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `inst_tipo_inst_otros` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `inst_dir_manz` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `inst_dir_torre_monob_nro` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `inst_dir_dpto_ofi_casa_nro` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `inst_dir_esc_pasillo` ENUM('Escalera', 'Pasillo') CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `inst_dir_esc_pasillo_nro` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `inst_dir_vec_asent_nro` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `inst_dir_torre_monob` ENUM('Torre', 'Monoblock') CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `inst_dir_ruta` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `inst_dir_ruta_km` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `inst_dir_vec_asent` ENUM('Vecinal', 'Asentamiento', 'Barrio') CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `inst_dir_ref_vis_geo` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `inst_dir_cod_pos` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `inst_nro` INT(11) NULL DEFAULT NULL,
  `Agrup_institucion` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `estado_reg` INT(11) NULL DEFAULT NULL,
  `localidad` INT(11) NULL DEFAULT NULL,
  `tipo_institucion` INT(11) NULL DEFAULT NULL,
  `clave_pago` INT(11) NULL DEFAULT NULL,
  `ipec_calle` INT(11) NULL DEFAULT NULL,
  `estatuto` VARCHAR(1024) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `institucion_geo` INT(11) NULL DEFAULT NULL,
  `fortalecimiento` INT(11) NULL DEFAULT NULL,
  `inst_nro_enc` INT(11) NULL DEFAULT NULL,
  `ID_TIPO` INT(11) NULL DEFAULT NULL,
  `mutual` ENUM('Si', 'No') CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `cuenta_bancaria` ENUM('Si', 'No') CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `sipaf` ENUM('Si', 'No') CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`inst_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 7967
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `desoc_buenaspracticas`.`actoAdministrativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desoc_buenaspracticas`.`actoAdministrativo` (
  `idActoAdministrativo` INT NOT NULL AUTO_INCREMENT,
  `nroNota` INT NOT NULL,
  `fechaNota` DATE NOT NULL,
  `descripcionProyecto` TEXT NOT NULL,
  `montoSolicitado` DOUBLE NOT NULL,
  `montoAprobado` DOUBLE NULL,
  `fechaMontoAprobado` DOUBLE NULL,
  `observacion` VARCHAR(255) NULL,
  `referente` TEXT NOT NULL COMMENT 'emisor de la nota / pedido',
  `contactoApenom` VARCHAR(45) NULL,
  `contactoTe` VARCHAR(45) NOT NULL,
  `contactoMail` VARCHAR(45) NULL,
  `tramiteUrgente` TINYINT(1) NOT NULL DEFAULT 0,
  `tipoSolicitante_idtipoSolicitante` INT NOT NULL,
  `Institucion_inst_id` INT NOT NULL,
  `nombreInstitucion` VARCHAR(45) NULL,
  `idLocalidadInst` INT NOT NULL,
  `localidadInst` VARCHAR(45) NOT NULL,
  `departamentoInst` VARCHAR(45) NOT NULL,
  `cbuInstitucion` VARCHAR(22) NULL,
  `nroExpediente` VARCHAR(45) NULL,
  `fechaExpediente` DATE NULL,
  `caratula` TEXT NULL,
  `fechaCaratula` DATE NULL,
  `fechaDictamen` DATE NULL,
  `observacionDictamen` TEXT NULL,
  `etapas` VARCHAR(45) NULL DEFAULT '1',
  `usuario` VARCHAR(45) NULL,
  `fechaCarga` DATETIME NULL,
  `fechaBaja` DATETIME NULL,
  `motivoBaja` VARCHAR(255) NULL,
  `cantidadBenefDirectos` INT NULL,
  `cantidadBenefIndirectos` INT NULL,
  PRIMARY KEY (`idActoAdministrativo`),
  INDEX `fecha_solicitud` (`fechaNota` ASC),
  INDEX `fk_actoAdministrativo_tipoInstitucionBP1_idx` (`tipoSolicitante_idtipoSolicitante` ASC),
  INDEX `fk_actoAdministrativo_Institucion1_idx` (`Institucion_inst_id` ASC),
  CONSTRAINT `fk_actoAdministrativo_tipoInstitucionBP1`
    FOREIGN KEY (`tipoSolicitante_idtipoSolicitante`)
    REFERENCES `desoc_buenaspracticas`.`tipoSolicitante` (`idtipoSolicitante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actoAdministrativo_Institucion1`
    FOREIGN KEY (`Institucion_inst_id`)
    REFERENCES `mds_ruinstituciones`.`Institucion` (`inst_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `desoc_buenaspracticas`.`observaciones_bp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desoc_buenaspracticas`.`observaciones_bp` (
  `idObservacionActoAdministrativo` INT NOT NULL AUTO_INCREMENT,
  `observacion` TEXT NOT NULL,
  `fechaObs` DATE NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `fechaCarga` DATETIME NOT NULL,
  `actoAdministrativo_idActoAdministrativo` INT NOT NULL,
  PRIMARY KEY (`idObservacionActoAdministrativo`),
  INDEX `fecha_obs` (`fechaObs` ASC),
  INDEX `fk_observaciones_bp_actoAdministrativo1_idx` (`actoAdministrativo_idActoAdministrativo` ASC),
  CONSTRAINT `fk_observaciones_bp_actoAdministrativo1`
    FOREIGN KEY (`actoAdministrativo_idActoAdministrativo`)
    REFERENCES `desoc_buenaspracticas`.`actoAdministrativo` (`idActoAdministrativo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `desoc_buenaspracticas`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desoc_buenaspracticas`.`area` (
  `idArea` INT NOT NULL AUTO_INCREMENT,
  `area` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idArea`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `desoc_buenaspracticas`.`componente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desoc_buenaspracticas`.`componente` (
  `idComponente` INT NOT NULL AUTO_INCREMENT,
  `componente` VARCHAR(100) NULL,
  PRIMARY KEY (`idComponente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `desoc_buenaspracticas`.`movimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desoc_buenaspracticas`.`movimiento` (
  `idMovimiento` INT NOT NULL AUTO_INCREMENT,
  `area_idAreaOrigen` INT NOT NULL,
  `area_idAreaDestino` INT NOT NULL,
  `fechaMovimiento` DATETIME NULL,
  `motivoMovimiento` ENUM('Continuar trámite', 'Solicitar revision', 'A evaluar', 'A dictaminar', 'A pagar') NULL,
  `observacion` TEXT NULL,
  `folios` INT NULL,
  `fechaCarga` DATETIME NULL,
  `usuario` VARCHAR(45) NULL,
  `actoAdministrativo_idActoAdministrativo` INT NOT NULL,
  `tipoMovimiento` ENUM('INTERNO', 'EXTERNO') NOT NULL DEFAULT 'INTERNO',
  PRIMARY KEY (`idMovimiento`),
  INDEX `fk_Movimiento_area1_idx` (`area_idAreaOrigen` ASC),
  INDEX `fk_Movimiento_actoAdministrativo1_idx` (`actoAdministrativo_idActoAdministrativo` ASC),
  CONSTRAINT `fk_Movimiento_area1`
    FOREIGN KEY (`area_idAreaOrigen`)
    REFERENCES `desoc_buenaspracticas`.`area` (`idArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movimiento_actoAdministrativo1`
    FOREIGN KEY (`actoAdministrativo_idActoAdministrativo`)
    REFERENCES `desoc_buenaspracticas`.`actoAdministrativo` (`idActoAdministrativo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `desoc_buenaspracticas`.`actoAdministrativo_has_componente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desoc_buenaspracticas`.`actoAdministrativo_has_componente` (
  `idActoAdministrativo_has_componente` INT NOT NULL AUTO_INCREMENT,
  `actoAdministrativo_idActoAdministrativo` INT NOT NULL,
  `componente_idComponenteSolicitado` INT NOT NULL,
  `detalleComponente_idDetalleComponenteSolicitado` INT NOT NULL,
  `fechaSolicitado` DATETIME NULL,
  `componente_idComponenteAprobado` INT NULL,
  `detalleComponente_idDetalleComponenteAprobado` INT NULL,
  `fechaAprobado` DATETIME NULL,
  PRIMARY KEY (`idActoAdministrativo_has_componente`),
  INDEX `fk_actoAdministrativo_has_componente_componente1_idx` (`componente_idComponenteSolicitado` ASC),
  INDEX `fk_actoAdministrativo_has_componente_actoAdministrativo1_idx` (`actoAdministrativo_idActoAdministrativo` ASC),
  CONSTRAINT `fk_actoAdministrativo_has_componente_actoAdministrativo1`
    FOREIGN KEY (`actoAdministrativo_idActoAdministrativo`)
    REFERENCES `desoc_buenaspracticas`.`actoAdministrativo` (`idActoAdministrativo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actoAdministrativo_has_componente_componente1`
    FOREIGN KEY (`componente_idComponenteSolicitado`)
    REFERENCES `desoc_buenaspracticas`.`componente` (`idComponente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `desoc_buenaspracticas`.`detalleComponente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desoc_buenaspracticas`.`detalleComponente` (
  `iddetalleComponente` INT NOT NULL AUTO_INCREMENT,
  `detalleComponente` VARCHAR(100) NULL,
  `componente_idComponente` INT NOT NULL,
  PRIMARY KEY (`iddetalleComponente`, `componente_idComponente`),
  INDEX `fk_detalleComponente_componente1_idx` (`componente_idComponente` ASC),
  CONSTRAINT `fk_detalleComponente_componente1`
    FOREIGN KEY (`componente_idComponente`)
    REFERENCES `desoc_buenaspracticas`.`componente` (`idComponente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `desoc_buenaspracticas`.`estadoActoAdministrativo_has_actoAdministrativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desoc_buenaspracticas`.`estadoActoAdministrativo_has_actoAdministrativo` (
  `idestadoActo_has_actoAdministrativo` INT NOT NULL AUTO_INCREMENT,
  `estadoActoAdministrativo_idestado` INT NOT NULL,
  `actoAdministrativo_idActoAdministrativo` INT NOT NULL,
  `fechaEstado` DATE NOT NULL,
  `observacionEstado` TEXT NULL,
  `fechaCarga` DATETIME NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idestadoActo_has_actoAdministrativo`),
  INDEX `fk_estadoActoAdministrativo_has_actoAdministrativo_actoAdmi_idx` (`actoAdministrativo_idActoAdministrativo` ASC),
  INDEX `fk_estadoActoAdministrativo_has_actoAdministrativo_estadoAc_idx` (`estadoActoAdministrativo_idestado` ASC),
  CONSTRAINT `fk_estadoActoAdministrativo_has_actoAdministrativo_estadoActo1`
    FOREIGN KEY (`estadoActoAdministrativo_idestado`)
    REFERENCES `desoc_buenaspracticas`.`estadoActoAdministrativo` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estadoActoAdministrativo_has_actoAdministrativo_actoAdmini1`
    FOREIGN KEY (`actoAdministrativo_idActoAdministrativo`)
    REFERENCES `desoc_buenaspracticas`.`actoAdministrativo` (`idActoAdministrativo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `desoc_buenaspracticas`.`checkRequisitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desoc_buenaspracticas`.`checkRequisitos` (
  `idcheckRequisitos` INT NOT NULL AUTO_INCREMENT,
  `detalleRequisito` VARCHAR(45) NULL,
  `validoPara` VARCHAR(45) NULL,
  `fechaBaja` DATETIME NULL,
  PRIMARY KEY (`idcheckRequisitos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `desoc_buenaspracticas`.`actoAdministrativo_has_checkRequisitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desoc_buenaspracticas`.`actoAdministrativo_has_checkRequisitos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `actoAdministrativo_idActoAdministrativo` INT NOT NULL,
  `checkRequisitos_idcheckRequisitos` INT NOT NULL,
  `fechaControl` DATETIME NULL,
  `observacion` VARCHAR(255) NULL,
  `fechaCarga` DATETIME NULL,
  `usuario` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `actoAdministrativo_idActoAdministrativo`, `checkRequisitos_idcheckRequisitos`),
  INDEX `fk_actoAdministrativo_has_checkRequisitos_checkRequisitos1_idx` (`checkRequisitos_idcheckRequisitos` ASC),
  INDEX `fk_actoAdministrativo_has_checkRequisitos_actoAdministrativ_idx` (`actoAdministrativo_idActoAdministrativo` ASC),
  CONSTRAINT `fk_actoAdministrativo_has_checkRequisitos_actoAdministrativo1`
    FOREIGN KEY (`actoAdministrativo_idActoAdministrativo`)
    REFERENCES `desoc_buenaspracticas`.`actoAdministrativo` (`idActoAdministrativo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actoAdministrativo_has_checkRequisitos_checkRequisitos1`
    FOREIGN KEY (`checkRequisitos_idcheckRequisitos`)
    REFERENCES `desoc_buenaspracticas`.`checkRequisitos` (`idcheckRequisitos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `desoc_buenaspracticas`.`autoridad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desoc_buenaspracticas`.`autoridad` (
  `idautoridad` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(8) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `idpersonas` INT NOT NULL,
  `actoAdministrativo_idActoAdministrativo` INT NOT NULL,
  PRIMARY KEY (`idautoridad`),
  INDEX `fk_autoridad_actoAdministrativo1_idx` (`actoAdministrativo_idActoAdministrativo` ASC),
  CONSTRAINT `fk_autoridad_actoAdministrativo1`
    FOREIGN KEY (`actoAdministrativo_idActoAdministrativo`)
    REFERENCES `desoc_buenaspracticas`.`actoAdministrativo` (`idActoAdministrativo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `desoc_buenaspracticas`.`Autoridad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desoc_buenaspracticas`.`Autoridad` (
  `aut_id` INT(11) NOT NULL AUTO_INCREMENT,
  `doctrine_version` INT(11) NOT NULL DEFAULT '1',
  `aut_ape` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `aut_nom` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `aut_doc` INT(11) NULL DEFAULT NULL,
  `aut_fec_nac` DATE NULL DEFAULT NULL,
  `aut_cuil_cdi` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `aut_sexo` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `aut_telefono` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `aut_celular` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `aut_mail` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `aut_cargo_fec_ini` DATE NULL DEFAULT NULL,
  `aut_cargo_fec_fin` DATE NULL DEFAULT NULL,
  `aut_dir_calle` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `aut_dir_nro` INT(11) NULL DEFAULT NULL,
  `aut_dir_piso` INT(11) NULL DEFAULT NULL,
  `aut_dir_dpto_ofi_casa` ENUM('Dpto', 'Oficina', 'Casa') CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `aut_dir_dpto_ofi_casa_nro` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `aut_dir_manz` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `aut_dir_torre_monob` ENUM('Torre', 'Monoblock') CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `aut_dir_torre_monob_nro` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `aut_dir_esc_pasillo` ENUM('Escalera', 'Pasillo') CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `aut_dir_esc_pasillo_nro` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `aut_dir_vec_asent` ENUM('Vecinal', 'Asentamiento', 'Barrio') CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `aut_dir_vec_asent_nro` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `aut_dir_ruta` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `aut_dir_ruta_km` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `aut_dir_ref_vis_geo` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `aut_dir_cod_pos` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `tipo_documento` INT(11) NULL DEFAULT NULL,
  `cargo_autoridad` INT(11) NULL DEFAULT NULL,
  `nacionalidad` INT(11) NULL DEFAULT NULL,
  `t_persona` INT(11) NULL DEFAULT NULL,
  `localidad` INT(11) NULL DEFAULT NULL,
  `vinculo` INT(11) NULL DEFAULT NULL,
  `comision_directiva` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`aut_id`),
  INDEX `IDX_2C0B5FFF54DF9189` (`tipo_documento` ASC),
  INDEX `IDX_2C0B5FFF6AE56588` (`cargo_autoridad` ASC),
  INDEX `IDX_2C0B5FFF931D5FC3` (`nacionalidad` ASC),
  INDEX `IDX_2C0B5FFFBC90EF8` (`t_persona` ASC),
  INDEX `IDX_2C0B5FFF4F68E010` (`localidad` ASC),
  INDEX `IDX_2C0B5FFF74C107E5` (`vinculo` ASC),
  INDEX `IDX_2C0B5FFF79987C8` (`comision_directiva` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 1314
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `desoc_buenaspracticas`.`Cargo_Autoridad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desoc_buenaspracticas`.`Cargo_Autoridad` (
  `cargo_aut_id` INT(11) NOT NULL AUTO_INCREMENT,
  `doctrine_version` INT(11) NOT NULL DEFAULT '1',
  `cargo_aut_desc` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`cargo_aut_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `desoc_buenaspracticas`.`Comision_Directiva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desoc_buenaspracticas`.`Comision_Directiva` (
  `com_dir_id` INT(11) NOT NULL AUTO_INCREMENT,
  `doctrine_version` INT(11) NOT NULL DEFAULT '1',
  `com_dir_fec_ini` DATE NULL DEFAULT NULL,
  `com_dir_fec_fin` DATE NULL DEFAULT NULL,
  `com_dir_activa` TINYINT(1) NULL DEFAULT NULL,
  `institucion` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`com_dir_id`),
  INDEX `IDX_D65D9A6BF751F7C3` (`institucion` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 815
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `desoc_buenaspracticas`.`Estado_Reg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desoc_buenaspracticas`.`Estado_Reg` (
  `est_reg_id` INT(11) NOT NULL AUTO_INCREMENT,
  `doctrine_version` INT(11) NOT NULL DEFAULT '1',
  `est_reg_nom` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`est_reg_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `desoc_buenaspracticas`.`Tipo_Institucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desoc_buenaspracticas`.`Tipo_Institucion` (
  `tip_inst_id` INT(11) NOT NULL AUTO_INCREMENT,
  `doctrine_version` INT(11) NOT NULL DEFAULT '1',
  `tip_inst_desc` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`tip_inst_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 118
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `desoc_buenaspracticas`.`t_loc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desoc_buenaspracticas`.`t_loc` (
  `id_loc` INT(11) NOT NULL DEFAULT '0',
  `circ` INT(11) NULL DEFAULT NULL,
  `loc` CHAR(50) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `depto` CHAR(50) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `id_nodo` INT(11) NULL DEFAULT NULL,
  `microregion` CHAR(1) CHARACTER SET 'latin1' COLLATE 'latin1_spanish_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id_loc`),
  INDEX `loc` (`loc` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
